#!/bin/bash
#
# antizapret-custom-dns — per-domain DNS overrides for AntiZapret VPN.
#
# Installed as /root/antizapret/custom-dns.sh and invoked from the
# custom-doall.sh hook (so it survives AntiZapret updates and re-applies daily).
#
# Reads:
#   /root/antizapret/config/custom-bind.txt      <домен> <IP[,IP2,...]>     -> static A answer       (policy.ANSWER)
#   /root/antizapret/config/custom-upstream.txt  <домен> <резолвер[,...]>   -> per-domain forwarder  (policy.FORWARD)
#
# Does:
#   1. generates /etc/knot-resolver/custom.lua from the two config files (with validation)
#   2. ensures kresd.conf loads custom.lua in both instances (self-healing, idempotent)
#   3. reloads kresd only when something changed
#
# Priority of resolution: bind > upstream > AntiZapret VPN routing.

set -u

AZ_DIR=/root/antizapret
CONF_DIR="$AZ_DIR/config"
KRESD_CONF=/etc/knot-resolver/kresd.conf
CUSTOM_LUA=/etc/knot-resolver/custom.lua
MARK='custom-dns-overrides'

is_ipv4() {
	[[ "$1" =~ ^([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})\.([0-9]{1,3})$ ]] || return 1
	local o; for o in "${BASH_REMATCH[@]:1:4}"; do (( o <= 255 )) || return 1; done
}

emit_rules() {
	local file domain addrs ip rdata
	# bind goes first → higher priority than upstream
	for file in "$CONF_DIR"/*custom-bind.txt; do
		[[ -e "$file" ]] || continue
		while read -r domain addrs; do
			[[ -z "${domain:-}" || "$domain" == \#* ]] && continue
			domain="${domain,,}"
			[[ "$domain" =~ ^[a-z0-9.-]+$ ]] || { echo "-- skip invalid bind domain: $domain"; continue; }
			rdata=''
			for ip in ${addrs//,/ }; do is_ipv4 "$ip" && rdata+="kres.str2ip('$ip'),"; done
			[[ -z "$rdata" ]] && { echo "-- skip bind without valid IP: $domain"; continue; }
			echo "policy.add(policy.suffix(policy.ANSWER({[kres.type.A] = {rdata = {${rdata%,}}, ttl = 300}}), policy.todnames({'$domain'})))"
		done < "$file"
	done
	# upstream
	for file in "$CONF_DIR"/*custom-upstream.txt; do
		[[ -e "$file" ]] || continue
		while read -r domain addrs; do
			[[ -z "${domain:-}" || "$domain" == \#* ]] && continue
			domain="${domain,,}"
			[[ "$domain" =~ ^[a-z0-9.-]+$ ]] || { echo "-- skip invalid upstream domain: $domain"; continue; }
			rdata=''
			for ip in ${addrs//,/ }; do is_ipv4 "$ip" && rdata+="'$ip',"; done
			[[ -z "$rdata" ]] && { echo "-- skip upstream without valid resolver: $domain"; continue; }
			echo "policy.add(policy.suffix(policy.FORWARD({${rdata%,}}), policy.todnames({'$domain'})))"
		done < "$file"
	done
}

changed=0

# 1) Generate custom.lua
TMP_LUA="$(mktemp)"
{
	echo "-- AUTO-GENERATED by custom-dns.sh from config/custom-bind.txt and config/custom-upstream.txt"
	echo "-- Do not edit manually. Priority: bind > upstream > AntiZapret routing."
	emit_rules
} > "$TMP_LUA"
if ! diff -q "$TMP_LUA" "$CUSTOM_LUA" >/dev/null 2>&1; then
	install -m 0644 "$TMP_LUA" "$CUSTOM_LUA"
	changed=1
fi
rm -f "$TMP_LUA"

# 2) Ensure kresd.conf loads custom.lua (self-healing, idempotent).
#    Inject right after the "NO_EDNS" FLAGS line in each instance — i.e. after the
#    adblock deny.rpz, before proxy.rpz/forwarders, so custom overrides win over
#    VPN routing but adblock and HTTPS/AAAA handling still take precedence.
if [[ -f "$KRESD_CONF" ]] && ! grep -q "$MARK" "$KRESD_CONF"; then
	TMP_CONF="$(mktemp)"
	if awk -v q="'" '
		{
			print
			if ($0 ~ /policy\.all\(policy\.FLAGS\(\{.*NO_EDNS/) {
				print "\t-- custom-dns-overrides BEGIN"
				print "\tdo local f = io.open(" q "/etc/knot-resolver/custom.lua" q "); if f then f:close(); dofile(" q "/etc/knot-resolver/custom.lua" q ") end end"
				print "\t-- custom-dns-overrides END"
				n++
			}
		}
		END { exit (n+0 == 0 ? 9 : 0) }
	' "$KRESD_CONF" > "$TMP_CONF"; then
		cp -f "$KRESD_CONF" "$KRESD_CONF.bak.$(date +%Y%m%d-%H%M%S)"
		install -m 0644 "$TMP_CONF" "$KRESD_CONF"
		changed=1
		echo "custom-dns: injected dofile into $KRESD_CONF"
	else
		echo "custom-dns: WARNING — FLAGS anchor not found in $KRESD_CONF, custom.lua NOT wired" >&2
	fi
	rm -f "$TMP_CONF"
fi

# 3) Reload kresd only on change
if [[ "$changed" -eq 1 ]]; then
	systemctl reload-or-restart kresd@1 kresd@2 2>/dev/null || systemctl restart kresd@1 kresd@2 2>/dev/null || true
	echo "custom-dns: applied $(grep -c '^policy.add' "$CUSTOM_LUA" 2>/dev/null || echo 0) rule(s), kresd reloaded"
else
	echo "custom-dns: no changes"
fi

exit 0
